language: perl
perl:
  - "5.8"
  - "5.10"
  - "5.12"
  - "5.14"
  - "5.16"
  - "5.18"
before_install:
 - sudo apt-get update -qq
 - sudo apt-get install -qq libmysqlclient-dev
 - perlbrew install-cpanm -f
install:
  - cpanm --verbose DBI Test::Pod Test::Deep Test::DistManifest Proc::ProcessTable
script: "export EXTENDED_TESTING=1 && export RELEASE_TESTING=1 && perl Makefile.PL && make disttest"
